version: "3.9"
services:
  ui:
    image: veyselceylan/userful-pages
    volumes:
      - ./src:/app/src
      - '/app/node_modules'
    build:
      context: .
      dockerfile: Dockerfile
      target: development-stage
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start
    ports:
      - "5173:5173"